version: '3.8'

services:
  fastapi-app:
    container_name: api 
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:80"
    depends_on:
      - mongo


  mongo:
    container_name: mongo_host
    image: "mongo:latest"  
    ports:
      - "27018:27017"
    
    volumes:
      - ./mongo-data:/data/db  
