version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_DATABASE: "API Wishlist"
      MONGO_INITDB_ROOT_USERNAME: "raissabxdev"
      MONGO_INITDB_ROOT_PASSWORD: "raissabxdev"
